spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      host: 192.168.106.2
      port: 35001
      database: example-stream
      authentication-database: admin

  kafka:
    bootstrap-servers: 192.168.106.2:9092
    schema-registry-url: http://192.168.106.2:8081
    consumer-group-id: uploader-1
    image-processor-input-topic: example-stream.image-processor

