spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      host: 192.168.106.2
      port: 35001
      database: example-stream
      authentication-database: admin