apiVersion: v1
kind: Service
metadata:
  name: example-mongo
  labels:
    app: example-mongo
    service: example-mongo
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: example-mongo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-mongo
  labels:
    account: example-mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-mongo
  labels:
    app: example-mongo
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-mongo
      version: v1
  template:
    metadata:
      labels:
        app: example-mongo
        version: v1
    spec:
      serviceAccountName: example-mongo
      containers:
        - name: example-mongo
          image: mongo:6.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
            - name: MONGO_INITDB_DATABASE
              value: example-stream