apiVersion: v1
kind: ServiceAccount
metadata:
  name: diff-checker
  labels:
    account: diff-checker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diff-checker
  labels:
    app: diff-checker
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diff-checker
      version: v1
  template:
    metadata:
      labels:
        app: diff-checker
        version: v1
    spec:
      serviceAccountName: diff-checker
      containers:
        - name: diff-checker
          image: 127.0.0.1:5001/diff-checker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
