apiVersion: v1
kind: Service
metadata:
  name: product-collector
  labels:
    app: product-collector
    service: product-collector
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: product-collector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-collector
  labels:
    account: product-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-collector
  labels:
    app: product-collector
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-collector
      version: v1
  template:
    metadata:
      labels:
        app: product-collector
        version: v1
    spec:
      serviceAccountName: product-collector
      containers:
        - name: product-collector
          image: 127.0.0.1:5001/product-collector:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
