apiVersion: v1
kind: Service
metadata:
  name: example-product-collector
  labels:
    app: example-product-collector
    service: example-product-collector
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: example-product-collector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-product-collector
  labels:
    account: example-product-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-product-collector
  labels:
    app: example-product-collector
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-product-collector
      version: v1
  template:
    metadata:
      labels:
        app: example-product-collector
        version: v1
    spec:
      serviceAccountName: example-product-collector
      containers:
        - name: example-product-collector
          image: 192.168.106.2:5000/example-product-collector:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
